sudo: required
os:
    - linux
# trusty needed for docker
dist: trusty
language: python
python:
    - "3.6"
matrix:
    include:
    - python: "3.6"
      env: SYN_TEST_CORE="ram"
    - python: "3.6"
      env: SYN_TEST_CORE="sqlite"
    - python: "3.6"
      env: SYN_TEST_CORE="postgres"
services:
    - docker
install:
    - docker --version
    - python synapse/tests/travis/install.py
before_script:
    - python synapse/tests/travis/before_script.py
script: python synapse/tests/travis/script.py
after_success:
    - coveralls
