sudo: required
os:
    - linux
language: python
python:
    - "3.6"
matrix:
    include:
    - python: "2.7"
      env: SYN_TEST_CORE="py"
    - python: "3.4"
      env: SYN_TEST_CORE="py"
    - python: "3.5"
      env: SYN_TEST_CORE="py"
    - python: "3.6"
      env: SYN_TEST_CORE="ram"
    - python: "3.6"
      env: SYN_TEST_CORE="sqlite"
    - python: "3.6"
      env: SYN_TEST_CORE="postgres"
addons:
    postgresql: "9.6"
services:
    - docker
install:
    - which docker
    - python synapse/tests/travis/install.py
before_script:
    - python synapse/tests/travis/before_script.py
script: python synapse/tests/travis/script.py
after_success:
    - coveralls
