sudo: required
os:
    - linux
language: python
python:
    - "2.7"
    - "3.4"
env:
    - SYN_TEST_PG_DB=syn_test
    - SYN_PY27=1
    - SYN_PY35=1
    - SYN_PY36=1
    - SYN_CORE_RAM=1
    - SYN_CORE_SQLITE=1
    - SYN_CORE_PG95=1
matrix:
    exclude:
    - python: "2.7"
        env: SYN_PY27=1
    - python: "2.7"
        env: SYN_PY35=1
    - python: "2.7"
        env: SYN_PY36=1
    - python: "2.7"
        env: SYN_CORE_RAM=1
    - python: "2.7"
        env: SYN_CORE_SQLITE=1
    - python: "2.7"
        env: SYN_CORE_PG95=1
services:
    - postgresql
    - docker
install:
    - python setup.py install
    - pip install psycopg2 coverage coveralls
    - python -m synapse.tests.travis.install
before_script:
    - psql -c 'create database syn_test;' -U postgres
    - python -m synapse.tests.travis.before_script
script: python -m synapse.tests.travis.script
after_success:
    - coveralls
