sudo: required
os:
    - linux
language: python
python:
    - "2.7"
    - "3.4"
env:
    - SYN_TEST_PG_DB=syn_test
    - SYN_DOCKER=1
matrix:
  exclude:
  - python: "2.7"
    env: SYN_DOCKER=1
services:
    - postgresql
    - docker
install:
    - python setup.py install
    - pip install psycopg2 coverage coveralls
    - python -m synapse.tests.travis.install
before_script:
    - psql -c 'create database syn_test;' -U postgres
    - python -m synapse.tests.travis.before_script
script: nosetests --verbosity=3 --stop --with-coverage --cover-package=synapse
after_success:
    - coveralls
