os:
    - linux
language: python
python:
    - "2.7"
    - "3.4"
install:
    - pip install msgpack-python tornado requests cryptography psycopg2 coverage coveralls pyOpenSSL
    - echo $TRAVIS_PYTHON_VERSION
    - echo $SYN_DOCKER
    - test $SYN_DOCKER = 1 \
        && docker build -t vertexproject/synapse -f synapse/docker/synapse_dockerfile . \
        && docker build -t vertexproject/cortex_ram -f synapse/docker/cortex/ram_dockerfile . \
        && docker run -d -p 127.0.0.1:47320:47322 --name cortex_ram vertexproject/cortex_ram 
script: nosetests --verbosity=3 -x --with-coverage --cover-package=synapse
services: 
    - postgresql
    - docker
before_script:
    - psql -c 'create database syn_test;' -U postgres
    - echo $TRAVIS_PYTHON_VERSION
    - echo $SYN_DOCKER
    - test $SYN_DOCKER = 1 \
        && docker ps | grep -q cortex_ram \
        && docker ps -a \
        && nc -v -w 4 127.0.0.1 47320
env:
    - SYN_COR_PG_DB=syn_test
    - SYN_DOCKER=1
matrix:
  exclude:
  - python: "2.7"
    env: SYN_DOCKER=1
after_success:
    - coveralls
