sudo: required
os:
    - linux
# trusty needed for docker
dist: trusty
language: python
python:
    - "3.6"
env:
    - SYN_TEST_CORE=py
    - SYN_TEST_CORE=ram
    - SYN_TEST_CORE=sqlite
    - SYN_TEST_CORE=postgres
matrix:
    include:
    - python: "3.6"
      env: SYN_TEST_DB_PG="syn_test"
addons:
    postgresql: "9.6"
services:
    - docker
install:
    - docker --version
    - python synapse/tests/travis/install.py
before_script:
    - python synapse/tests/travis/before_script.py
script: python synapse/tests/travis/script.py
after_success:
    - coveralls
