sudo: required
os:
    - linux
language: python
matrix:
    exclude:
    - python:
    include:
    - python: "2.7"
      env: SYN_TEST_CORE="py"
    - python: "3.4"
      env: SYN_TEST_CORE="py"
    - python: "3.5"
      env: SYN_TEST_CORE="py"
    - python: "3.6"
      env: SYN_TEST_CORE="ram"
    - python: "3.6"
      env: SYN_TEST_CORE="sqlite"
    - python: "3.6"
      env: SYN_TEST_CORE="postgres"
    - python: "3.6"
      env: SYN_TEST_DB_PG="syn_test"
addons:
    postgresql: "9.6"
services:
    - docker
install:
    - python synapse/tests/travis/install.py
before_script:
    - python -m synapse.tests.travis.before_script
script: python -m synapse.tests.travis.script
after_success:
    - coveralls
